# Generated by Django 3.2.4 on 2021-06-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturermodel',
            name='engine_vol',
            field=models.FloatField(null=True),
        ),
    ]
