# Generated by Django 3.2.4 on 2021-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_manufacturermodel_engine_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturermodel',
            name='fuel_type',
            field=models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Methane', 'Methane'), ('Electrical', 'Electrical')], max_length=10, null=True),
        ),
    ]
