# Generated by Django 3.2.4 on 2021-06-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_manufacturermodel_fuel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Methane', 'Methane'), ('Electrical', 'Electrical')], max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bgregnumber',
            name='man_model',
        ),
        migrations.RemoveField(
            model_name='bgregnumber',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='manufacturermodel',
            name='engine_vol',
        ),
        migrations.RemoveField(
            model_name='manufacturermodel',
            name='first_reg',
        ),
        migrations.RemoveField(
            model_name='manufacturermodel',
            name='fuel_type',
        ),
        migrations.AddField(
            model_name='manufacturermodel',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.manufacturer'),
        ),
        migrations.AlterField(
            model_name='manufacturermodel',
            name='man_model',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='CurrentVehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_vol', models.FloatField(null=True)),
                ('first_reg', models.CharField(max_length=10, null=True)),
                ('bg_reg_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.bgregnumber')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.fueltype')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.manufacturer')),
                ('manufacturer_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.manufacturermodel')),
            ],
        ),
    ]
